name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: yarn install
    - run: yarn run build
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git --work-tree build add --all
    - run: git commit -m "Automatic Build and Deploy run by GitHub Actions"
    - run: git push origin HEAD:gh-pages --force
